name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test and upload coverage data
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: xcodebuild clean test -destination 'name=iPhone 8' -scheme AdvancedList -enableCodeCoverage YES -derivedDataPath .build/derivedData -quiet
    - name: Upload Test coverage data
      run: bash <(curl -s https://codecov.io/bash) -J '^AdvancedList$' -D .build/derivedData
